create table categories (
	id BIGINT generated always as IDENTITY PRIMARY KEY, 
	name varchar(255) not null unique
);

insert into categories (name) values 
('Desktop'),
('Notebooks'),
('Servidores'),
('Monitores'),
('Teclados'),
('Mouses'),
('Nobreaks'),
('Estabilizadores'),
('Fontes de Energia'),
('Extensões Elétricas'),
('Filtros de Linha'),
('Cabos de Energia'),
('Cabos de Rede'),
('Cabos HDMI'),
('Cabos DisplayPort'),
('Cabos VGA'),
('Switches'),
('Roteadores'),
('Access Points'),
('Firewalls'),
('Racks'),
('Patch Panels'),
('Storages'),
('HDs'),
('SSDs'),
('Pendrives'),
('Impressoras'),
('Scanners'),
('Webcams'),
('Headsets'),
('Telefones IP'),
('Placas de Rede'),
('Placas de Vídeo'),
('Memórias RAM'),
('Processadores'),
('Leitores de Código de Barras'),
('Projetores'),
('Tablets'),
('Smartphones Corporativos'),
('Licenças de Software'),
('Periféricos Diversos');